/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wubi_WubiCodeService */

#ifndef _Included_com_example_wubi_WubiCodeService
#define _Included_com_example_wubi_WubiCodeService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wubi_WubiCodeService
 * Method:    nativeQueryWubiCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_wubi_WubiCodeService_nativeQueryWubiCode
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
